# Generated by Django 4.1.2 on 2022-10-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocial',
            field=models.FloatField(default=0, verbose_name='Preço com desconto'),
        ),
    ]
