# Generated by Django 4.1.2 on 2022-10-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_alter_produto_preco_marketing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_marketing_promocial',
            new_name='preco_marketing_promocional',
        ),
    ]
